CreateConVar('ttt_mark_show_sidebar', 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_mark_show_messages', 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_mark_min_alive', 4, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_mark_max_to_mark', 9, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_mark_pct_marked', 0.75, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_mark_fixed_mark_amount', -1, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_mark_deal_no_damage', 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE})
CreateConVar('ttt_mark_take_no_damage', 1, {FCVAR_NOTIFY, FCVAR_ARCHIVE})