resource.AddFile("materials/vgui/ttt/dynamic/roles/icon_mark.vmt")
resource.AddFile("materials/vgui/ttt/hud_icon_marked.png")
resource.AddFile("materials/vgui/ttt/hud_icon_marked_end.png")
resource.AddFile("materials/vgui/ttt/icon_markergun.png")
resource.AddFile("materials/vgui/ttt/player_marked.png")

-- paintgun and paintball files
resource.AddFile("materials/models/paintball.vmt")

resource.AddFile("materials/models/weapons/blazer.vmt")
resource.AddFile("materials/models/weapons/blazer_normal.vtf")
resource.AddFile("materials/models/weapons/blazer_specmap.vtf")
resource.AddFile("materials/models/weapons/dpb_gravhopper_lid.vmt")
resource.AddFile("materials/models/weapons/dpb_gravhopper_main.vmt")
resource.AddFile("materials/models/weapons/dpb_gravhopper_main_normal.vtf")
resource.AddFile("materials/models/weapons/dpb_ppsbar_blk.vmt")
resource.AddFile("materials/models/weapons/drop_asa.vmt")
resource.AddFile("materials/models/weapons/hosefittings.vmt")
resource.AddFile("materials/models/weapons/newhandstex.vmt")
resource.AddFile("materials/models/weapons/pod_glass.vmt")
resource.AddFile("materials/models/weapons/pod_main.vmt")
resource.AddFile("materials/models/weapons/reg_stabilizer_black.vmt")
resource.AddFile("materials/models/weapons/w_blazer.vmt")

resource.AddFile("materials/decals/splat1.vmt")
resource.AddFile("materials/decals/splat2.vmt")
resource.AddFile("materials/decals/splat3.vmt")
resource.AddFile("materials/decals/splat4.vmt")
resource.AddFile("materials/decals/splat5.vmt")
resource.AddFile("materials/decals/splat6.vmt")
resource.AddFile("materials/decals/splat7.vmt")
resource.AddFile("materials/decals/splat8.vmt")
resource.AddFile("materials/decals/splat9.vmt")
resource.AddFile("materials/decals/splat10.vmt")
resource.AddFile("materials/decals/splat11.vmt")
resource.AddFile("materials/decals/splat12.vmt")

resource.AddFile("materials/paintball/paintball.vmt")
resource.AddFile("materials/paintball/paintball_solid.vmt")
resource.AddFile("materials/paintball/pb.vmt")

resource.AddFile("materials/sprites/pb.vmt")

resource.AddFile("models/paintball/paintball.dx80.vtx")
resource.AddFile("models/paintball/paintball.dx90.vtx")
resource.AddFile("models/paintball/paintball.mdl")
resource.AddFile("models/paintball/paintball.phy")
resource.AddFile("models/paintball/paintball.sw.vtx")
resource.AddFile("models/paintball/paintball.vvd")

resource.AddFile("models/weapons/v_blazer.dx80.vtx")
resource.AddFile("models/weapons/v_blazer.dx90.vtx")
resource.AddFile("models/weapons/v_blazer.mdl")
resource.AddFile("models/weapons/v_blazer.sw.vtx")
resource.AddFile("models/weapons/v_blazer.vvd")

resource.AddFile("models/weapons/w_blazer.dx80.vtx")
resource.AddFile("models/weapons/w_blazer.dx90.vtx")
resource.AddFile("models/weapons/w_blazer.mdl")
resource.AddFile("models/weapons/w_blazer.phy")
resource.AddFile("models/weapons/w_blazer.sw.vtx")
resource.AddFile("models/weapons/w_blazer.vvd")

resource.AddFile("sound/marker/pbfire.wav")
resource.AddFile("sound/marker/pbhit.wav")

resource.AddFile("materials/vgui/ttt/vskin/events/marked.vmt")

